"use client";

import { useState } from "react";
import { explainError } from "@/lib/api";

interface ExplainResult {
  error_type: string;
  root_cause: string;
  why_it_happened: string;
  impact: string;
  fix_suggestions: string[];
  code_example: string;
  prevention_tip: string;
  confidence: string;
}

const confidenceColor = (c: string) => {
  switch (c?.toLowerCase()) {
    case "high":   return "text-green-400 bg-green-400/10 border-green-400/30";
    case "medium": return "text-yellow-400 bg-yellow-400/10 border-yellow-400/30";
    case "low":    return "text-red-400 bg-red-400/10 border-red-400/30";
    default:       return "text-gray-400 bg-gray-400/10 border-gray-400/30";
  }
};

const examples = [
  `TimeoutError: Timeout 30000ms exceeded.
waiting for locator('#submit-btn')
  at LoginPage.clickSubmit (pages/login.py:45)`,

  `Error: element not interactable
  (Session info: chrome=120.0.6099.130)
  at Object.throwDecodedError (node_modules/selenium-webdriver)`,

  `{"error": "401 Unauthorized", "message": "JWT token expired", "code": "TOKEN_EXPIRED"}`,

  `ModuleNotFoundError: No module named 'playwright'
  File "tests/test_login.py", line 3, in <module>
  from playwright.sync_api import sync_playwright`,
];

export default function AIExplainPage() {
  const [errorInput, setErrorInput] = useState("");
  const [loading, setLoading]       = useState(false);
  const [result, setResult]         = useState<ExplainResult | null>(null);
  const [error, setError]           = useState("");
  const [copied, setCopied]         = useState(false);

  const handleExplain = async () => {
    if (!errorInput.trim()) {
      setError("Please paste an error to explain.");
      return;
    }
    setError("");
    setLoading(true);
    setResult(null);
    try {
      const data = await explainError({ error_input: errorInput });
      setResult(data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!result) return;
    const text = `
ROOT CAUSE: ${result.root_cause}

WHY IT HAPPENED: ${result.why_it_happened}

IMPACT: ${result.impact}

FIX SUGGESTIONS:
${result.fix_suggestions.map((f, i) => `${i + 1}. ${f}`).join("\n")}

${result.code_example ? `CODE EXAMPLE:\n${result.code_example}` : ""}

PREVENTION: ${result.prevention_tip}
    `.trim();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerateReport = () => {
    if (!result) return;
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>AI Error Report — TestForgeAI</title>
  <style>
    body { font-family: -apple-system, sans-serif; background: #0a0a0f; color: #e5e7eb; margin: 0; padding: 32px; }
    .container { max-width: 860px; margin: 0 auto; }
    h1 { color: #60a5fa; font-size: 24px; margin-bottom: 4px; }
    .meta { color: #6b7280; font-size: 13px; margin-bottom: 32px; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; border: 1px solid; margin-left: 8px; }
    .high { color: #4ade80; border-color: #4ade80; background: rgba(74,222,128,0.1); }
    .medium { color: #facc15; border-color: #facc15; background: rgba(250,204,21,0.1); }
    .low { color: #f87171; border-color: #f87171; background: rgba(248,113,113,0.1); }
    .section { background: #111827; border: 1px solid #1f2937; border-radius: 12px; padding: 20px; margin-bottom: 16px; }
    .section-title { color: #9ca3af; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 10px; }
    .section-content { color: #e5e7eb; font-size: 15px; line-height: 1.6; }
    .fix-item { display: flex; gap: 10px; margin-bottom: 8px; }
    .fix-num { color: #60a5fa; font-weight: 700; min-width: 20px; }
    pre { background: #0f172a; border: 1px solid #1e293b; border-radius: 8px; padding: 16px; overflow-x: auto; color: #4ade80; font-size: 13px; margin: 0; }
    .error-box { background: #1a0a0a; border: 1px solid #7f1d1d; border-radius: 8px; padding: 16px; font-family: monospace; font-size: 13px; color: #fca5a5; white-space: pre-wrap; word-break: break-all; }
    .footer { text-align: center; color: #374151; font-size: 12px; margin-top: 32px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🤖 AI Error Explanation Report
      <span class="badge ${result.confidence.toLowerCase()}">${result.confidence} Confidence</span>
    </h1>
    <div class="meta">Generated by TestForgeAI &nbsp;·&nbsp; ${new Date().toLocaleString()} &nbsp;·&nbsp; Error Type: ${result.error_type}</div>

    <div class="section">
      <div class="section-title">Original Error</div>
      <div class="error-box">${errorInput.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
    </div>

    <div class="section">
      <div class="section-title">Root Cause</div>
      <div class="section-content">${result.root_cause}</div>
    </div>

    <div class="section">
      <div class="section-title">Why It Happened</div>
      <div class="section-content">${result.why_it_happened}</div>
    </div>

    <div class="section">
      <div class="section-title">Impact</div>
      <div class="section-content">${result.impact}</div>
    </div>

    <div class="section">
      <div class="section-title">Fix Suggestions</div>
      <div class="section-content">
        ${result.fix_suggestions.map((f, i) => `
          <div class="fix-item">
            <span class="fix-num">${i + 1}.</span>
            <span>${f}</span>
          </div>`).join("")}
      </div>
    </div>

    ${result.code_example ? `
    <div class="section">
      <div class="section-title">Code Example</div>
      <pre>${result.code_example.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
    </div>` : ""}

    <div class="section">
      <div class="section-title">Prevention Tip</div>
      <div class="section-content">${result.prevention_tip}</div>
    </div>

    <div class="footer">TestForgeAI — AI-Powered QA Copilot</div>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = "testforgeai-error-report.html";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="min-h-screen bg-gray-950 text-white">
      {/* Header */}
      <div className="border-b border-gray-800 bg-gray-900/50">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <a href="/" className="text-gray-400 hover:text-white text-sm transition-colors">← Back</a>
            <span className="text-gray-700">|</span>
            <span className="text-blue-400 font-semibold">TestForgeAI</span>
          </div>
          <div className="flex items-center gap-2 text-xs text-gray-500">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></div>
            AI Ready
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-10">
        {/* Title */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-red-500/20 border border-red-500/30 flex items-center justify-center text-xl">🤖</div>
            <div>
              <h1 className="text-2xl font-bold text-white">AI Error Explainer</h1>
              <p className="text-gray-400 text-sm">Paste any error → Get root cause, reason and fix in seconds</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
          {/* Input — left */}
          <div className="lg:col-span-2 space-y-4">
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-5">
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Paste Your Error <span className="text-red-400">*</span>
              </label>
              <textarea
  value={errorInput}
  onChange={(e) => setErrorInput(e.target.value)}
  placeholder={"Paste console error, stack trace, or API error response here..."}
  className="w-full h-48 bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white text-sm placeholder-gray-500 focus:outline-none focus:border-red-500/60 resize-none font-mono"
/>
<div className="flex items-center justify-between mt-1.5">
  <p className="text-xs text-gray-600">Min 10 characters required</p>
  <p className={`text-xs ${errorInput.length < 10 ? "text-red-500" : "text-gray-500"}`}>
    {errorInput.length} chars
  </p>
</div>
            </div>

            {/* Examples */}
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-5">
              <p className="text-xs font-medium text-gray-400 mb-3 uppercase tracking-wider">Try an Example</p>
              <div className="space-y-2">
                {examples.map((ex, i) => (
                  <button
                    key={i}
                    onClick={() => setErrorInput(ex)}
                    className="w-full text-left text-xs text-gray-500 hover:text-red-400 bg-gray-800 hover:bg-gray-700 rounded-lg px-3 py-2 transition-all border border-gray-700 hover:border-red-500/40 font-mono truncate"
                  >
                    {ex.split("\n")[0]}
                  </button>
                ))}
              </div>
            </div>

            <button
              onClick={handleExplain}
              disabled={loading}
              className="w-full py-3.5 bg-red-600 hover:bg-red-500 disabled:bg-gray-700 disabled:cursor-not-allowed text-white font-bold rounded-xl transition-all text-sm"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                  </svg>
                  Analyzing Error...
                </span>
              ) : "🤖 Explain This Error"}
            </button>

            {error && (
              <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 text-red-400 text-sm">{error}</div>
            )}
          </div>

          {/* Output — right */}
          <div className="lg:col-span-3">
            {!result && !loading && (
              <div className="h-full min-h-96 bg-gray-900 border border-gray-800 rounded-xl flex items-center justify-center">
                <div className="text-center text-gray-600">
                  <div className="text-5xl mb-4">🤖</div>
                  <p className="text-lg font-medium text-gray-500">Explanation will appear here</p>
                  <p className="text-sm text-gray-600 mt-1">Root cause · Why it happened · Fix steps</p>
                </div>
              </div>
            )}

            {loading && (
              <div className="h-full min-h-96 bg-gray-900 border border-gray-800 rounded-xl flex items-center justify-center">
                <div className="text-center">
                  <div className="flex gap-1.5 justify-center mb-4">
                    {[0,1,2].map(i => (
                      <div key={i} className="w-2.5 h-2.5 bg-red-400 rounded-full animate-bounce" style={{ animationDelay: `${i * 0.15}s` }}/>
                    ))}
                  </div>
                  <p className="text-gray-400 text-sm">Analyzing your error...</p>
                  <p className="text-gray-600 text-xs mt-1">Finding root cause and fix</p>
                </div>
              </div>
            )}

            {result && (
              <div className="space-y-4">
                {/* Top bar */}
                <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center justify-between flex-wrap gap-3">
                  <div className="flex items-center gap-3">
                    <span className="text-xs text-gray-400">Error Type:</span>
                    <span className="text-sm text-white font-medium">{result.error_type}</span>
                    <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${confidenceColor(result.confidence)}`}>
                      {result.confidence} Confidence
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={handleCopy}
                      className="text-xs px-3 py-1.5 bg-gray-800 hover:bg-gray-700 text-gray-300 rounded-lg border border-gray-700 transition-all"
                    >
                      {copied ? "✓ Copied!" : "Copy"}
                    </button>
                    <button
                      onClick={handleGenerateReport}
                      className="text-xs px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-all font-medium"
                    >
                      📄 Download Report
                    </button>
                  </div>
                </div>

                {/* Root Cause */}
                <div className="bg-red-500/5 border border-red-500/20 rounded-xl p-5">
                  <p className="text-xs text-red-400 uppercase tracking-wider mb-2 font-medium">🔴 Root Cause</p>
                  <p className="text-white text-sm leading-relaxed font-medium">{result.root_cause}</p>
                </div>

                {/* Why it happened */}
                <div className="bg-orange-500/5 border border-orange-500/20 rounded-xl p-5">
                  <p className="text-xs text-orange-400 uppercase tracking-wider mb-2 font-medium">⚠ Why It Happened</p>
                  <p className="text-gray-300 text-sm leading-relaxed">{result.why_it_happened}</p>
                </div>

                {/* Impact */}
                <div className="bg-yellow-500/5 border border-yellow-500/20 rounded-xl p-5">
                  <p className="text-xs text-yellow-400 uppercase tracking-wider mb-2 font-medium">💥 Impact</p>
                  <p className="text-gray-300 text-sm leading-relaxed">{result.impact}</p>
                </div>

                {/* Fix Suggestions */}
                <div className="bg-green-500/5 border border-green-500/20 rounded-xl p-5">
                  <p className="text-xs text-green-400 uppercase tracking-wider mb-3 font-medium">✅ Fix Suggestions</p>
                  <div className="space-y-2">
                    {result.fix_suggestions?.map((fix, i) => (
                      <div key={i} className="flex gap-3 items-start">
                        <span className="text-green-400 font-bold text-sm min-w-5">{i + 1}.</span>
                        <p className="text-gray-300 text-sm leading-relaxed">{fix}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Code Example */}
                {result.code_example && (
                  <div className="bg-gray-900 border border-gray-800 rounded-xl p-5">
                    <p className="text-xs text-blue-400 uppercase tracking-wider mb-3 font-medium">💡 Code Example</p>
                    <pre className="text-green-400 text-xs font-mono bg-gray-800 rounded-lg p-4 overflow-x-auto whitespace-pre-wrap">
                      {result.code_example}
                    </pre>
                  </div>
                )}

                {/* Prevention */}
                <div className="bg-blue-500/5 border border-blue-500/20 rounded-xl p-5">
                  <p className="text-xs text-blue-400 uppercase tracking-wider mb-2 font-medium">🛡 Prevention Tip</p>
                  <p className="text-gray-300 text-sm leading-relaxed">{result.prevention_tip}</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}